[pytest]
norecursedirs = [".git", "old", "docs", "dist", "build"]
addopts = ["--strict-markers", "--strict-config", "-ra", "-nauto", "--cov"]
pythonpath = ["src"]
testpaths = ["tests"]
filterwarnings = []
markers = []
