line-length = 120

[lint]
select = [
  "ALL",
]

ignore = [
  "ISC001",  # The following rule may cause conflicts when used with the formatter
  "COM812",  # The following rule may cause conflicts when used with the formatter
]

[lint.per-file-ignores]
"**/tests/*" = [
  "S101",  # S101: Use of assert detected. Hey man, we do need asserts in pytest tests.
  "PLR2004",  # Magic value used in comparison are ok in tests.
  "INP001",  # INP001: File {filename} is part of an implicit namespace package. Add an __init__.py.
  "D100",  # D100: Missing docstring in public module.
  "D104",  # D104: Missing docstring in public package
]

"**/tests/**/*" = [
  "S101",  # S101: Use of assert detected. Hey man, we do need asserts in pytest tests.
  "PLR2004",  # Magic value used in comparison are ok in tests.
  "INP001",  # INP001: File {filename} is part of an implicit namespace package. Add an __init__.py.
  "D100",  # D100: Missing docstring in public module.
  "D104",  # D104: Missing docstring in public package
]

# Use Google-style docstrings.
[lint.pydocstyle]
convention = "google"

[lint.flake8-pytest-style]
fixture-parentheses = false
